config/routes.rb
NavDatavbase::Application.routes.draw do

  resources :stocks
  resources :components
  resources :etfs

  root to: "etfs#index"

end

app/models/bond.rb
class Bond < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/commodity.rb
class Commodity < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/component.rb
class Component < ActiveRecord::Base

  belongs_to :stock
  belongs_to :etf

end

app/models/etf.rb
class Etf < ActiveRecord::Base

  attr_accessible :sponsor, :name, :symbol, :fund_family_id, :net_assets, :yield, :inception_date, :legal_type, :fund_summary, :cash

  has_many :categories
  has_many :components

  has_many :stocks, through: :components

  def primary_csv_column
    "Composite Ticker"
  end

  def csv_row_names
    csv_row_names = [

    ]
  end
end

app/models/historical_dividends.rb
class HistoricalDividends < ActiveRecord::Base
  # attr_accessible :title, :body

end

app/models/historical_price.rb
class HistoricalPrice < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/options.rb
class Options < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :components

  has_many :etfs, through: :components
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  # GET /components
  # GET /components.json
  def index
    @components = Component.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @components }
    end
  end

  # GET /components/1
  # GET /components/1.json
  def show
    @component = Component.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @component }
    end
  end

  # GET /components/new
  # GET /components/new.json
  def new
    @component = Component.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @component }
    end
  end

  # GET /components/1/edit
  def edit
    @component = Component.find(params[:id])
  end

  # POST /components
  # POST /components.json
  def create
    @component = Component.new(params[:component])

    respond_to do |format|
      if @component.save
        format.html { redirect_to @component, notice: 'Component was successfully created.' }
        format.json { render json: @component, status: :created, location: @component }
      else
        format.html { render action: "new" }
        format.json { render json: @component.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /components/1
  # PUT /components/1.json
  def update
    @component = Component.find(params[:id])

    respond_to do |format|
      if @component.update_attributes(params[:component])
        format.html { redirect_to @component, notice: 'Component was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @component.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /components/1
  # DELETE /components/1.json
  def destroy
    @component = Component.find(params[:id])
    @component.destroy

    respond_to do |format|
      format.html { redirect_to components_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/etfs_controller.rb
class EtfsController < ApplicationController
  # GET /etfs
  # GET /etfs.json
  def index
    @etfs = Etf.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @etfs }
    end
  end

  # GET /etfs/1
  # GET /etfs/1.json
  def show
    @etf = Etf.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @etf }
    end
  end

  # GET /etfs/new
  # GET /etfs/new.json
  def new
    @etf = Etf.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @etf }
    end
  end

  # GET /etfs/1/edit
  def edit
    @etf = Etf.find(params[:id])
  end

  # POST /etfs
  # POST /etfs.json
  def create
    @etf = Etf.new(params[:etf])

    respond_to do |format|
      if @etf.save
        format.html { redirect_to @etf, notice: 'Etf was successfully created.' }
        format.json { render json: @etf, status: :created, location: @etf }
      else
        format.html { render action: "new" }
        format.json { render json: @etf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /etfs/1
  # PUT /etfs/1.json
  def update
    @etf = Etf.find(params[:id])

    respond_to do |format|
      if @etf.update_attributes(params[:etf])
        format.html { redirect_to @etf, notice: 'Etf was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @etf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etfs/1
  # DELETE /etfs/1.json
  def destroy
    @etf = Etf.find(params[:id])
    @etf.destroy

    respond_to do |format|
      format.html { redirect_to etfs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stocks }
    end
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @stock = Stock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stock }
    end
  end

  # GET /stocks/new
  # GET /stocks/new.json
  def new
    @stock = Stock.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stock }
    end
  end

  # GET /stocks/1/edit
  def edit
    @stock = Stock.find(params[:id])
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(params[:stock])

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render json: @stock, status: :created, location: @stock }
      else
        format.html { render action: "new" }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stocks/1
  # PUT /stocks/1.json
  def update
    @stock = Stock.find(params[:id])

    respond_to do |format|
      if @stock.update_attributes(params[:stock])
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/etfs_helper.rb
module EtfsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/etfs/_form.html.erb
<%= form_for(@etf) do |f| %>
  <% if @etf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@etf.errors.count, "error") %> prohibited this etf from being saved:</h2>

      <ul>
      <% @etf.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/etfs/edit.html.erb
<h1>Editing etf</h1>

<%= render 'form' %>

<%= link_to 'Show', @etf %> |
<%= link_to 'Back', etfs_path %>

app/views/etfs/index.html.erb
<h1>Listing etfs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @etfs.each do |etf| %>
  <tr>
    <td><%= link_to 'Show', etf %></td>
    <td><%= link_to 'Edit', edit_etf_path(etf) %></td>
    <td><%= link_to 'Destroy', etf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Etf', new_etf_path %>

app/views/etfs/new.html.erb
<h1>New etf</h1>

<%= render 'form' %>

<%= link_to 'Back', etfs_path %>

app/views/etfs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_etf_path(@etf) %> |
<%= link_to 'Back', etfs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NavDatavbase</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Listing stocks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stocks.each do |stock| %>
  <tr>
    <td><%= link_to 'Show', stock %></td>
    <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
    <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>